### PR TITLE
Changed mocap4r2_msgs to mocap_interfaces

### PR DESCRIPTION
**Pull request by Juancams**
First you need to update [mocap4r2](https://github.com/MOCAP4ROS2-Project/mocap4r2) for the CI to pass

### CODE REVIEW

**Comment by fmrico** [comment]
> First you need to update [mocap4r2](https://github.com/MOCAP4ROS2-Project/mocap4r2) for the CI to pass

me?

**Comment by Juancams** [comment]
> > First you need to update [mocap4r2](https://github.com/MOCAP4ROS2-Project/mocap4r2) for the CI to pass
> 
> me?

Not you, @aaggj JAJAJA

**Comment by aaggj** [comment]
I don't get it 😹

**Review by aaggj — COMMENTED** [review]
Thx

**Comment by Juancams** [comment]
Please test that everything works by following the steps

**Comment by Juancams** [comment]
Did it work?

**Comment by aaggj** [comment]
Nop, I don´t see the frame odom, neither the topic. In addition the topic marker is empty

**Comment by Juancams** [comment]
Follow the steps

**Comment by aaggj** [comment]
> Follow the steps

I have followed the steps in the mocap documentation and I have the same issues :S

**Comment by Juancams** [comment]
> > Follow the steps
> 
> I have followed the steps in the mocap documentation and I have the same issues :S

This [steps](https://mocap4ros2-project.github.io/getting_started/index.html)?

**Comment by jmguerreroh** [comment]
> > > Follow the steps
> > 
> > 
> > I have followed the steps in the mocap documentation and I have the same issues :S
> 
> This [steps](https://mocap4ros2-project.github.io/getting_started/index.html)?

I wrote those steps some time ago... do they still work or need an update?

**Comment by Juancams** [comment]
Any update?

**Comment by jmguerreroh** [comment]
Done, good job 👍🏻

**Pull request merged**
